name: Build Docker image

on:
  push:
    branches:
      - safeguard
  pull_request:
    branches:
      - safeguard
  workflow_dispatch:
    inputs:
      plugin_name:
        description: "Plugin Name"
        required: false
        default: "uniswap"

jobs:
  build:
    runs-on: Linux-ARM64
    if: ${{ github.ref == 'refs/heads/safeguard' }}
    permissions:
      id-token: write
      contents: read
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.DEFAULT_REGION }}

      # Login to AWS Artifacts ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Plugin Name
        run: echo "PLUGIN_NAME=${{ github.event.inputs.plugin_name || 'uniswap' }}" >> $GITHUB_ENV

      # Build images
      - name: Build docker image
        if: ${{ github.ref != 'refs/heads/safeguard' }}
        run: |
          echo "PLUGIN_NAME=$PLUGIN_NAME"
          docker buildx bake --provenance=false --load
        env:
          COMMIT_SHA: ${{ github.sha }}
          PLUGIN_NAME: ${{ env.PLUGIN_NAME }}
          USE_CACHE: 1

      # Build images and push it
      - name: Build, tag, and push docker image to Amazon ECR
        if: ${{ github.ref == 'refs/heads/safeguard' }}
        run: |
          echo "PLUGIN_NAME=$PLUGIN_NAME"
          docker buildx bake --provenance=false --push
        env:
          COMMIT_SHA: ${{ github.sha }}
          PLUGIN_NAME: ${{ env.PLUGIN_NAME }}
          USE_CACHE: 1
