name: Linux tests

on:
  push:
    branches: [ safeguard ]
  pull_request:
    branches: [ safeguard ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
          cache: false
      - name: Run tests
        run: go test -short ./...
        env:
          GOOS: linux
          GOARCH: 386
